### ISSUE TITLE
Solr Issues after Installation of RM 2.7.0 amp ACS 5.2.3 enterprise

### ISSUE THREAD

**Issue by srikanth-josyula** [Alfresco/records-management#11]
I am using alfresco 5.2.3 enterprise with solr6 search services. Everything works fine when I deploy our application custom code inside the alfresco-platform jar and alfresco-share jar. Now, when I install alfresco records management amp file, the search stops working. I am not able to search even a single document or folder. RM amp version: alfresco-rm-enterprise-repo-2.7.0.amp and alfresco-rm-enterprise-share-2.7.0.amp

NOTE: The versions of alfresco and RM are already in the supported stack as per the alfresco documentation link: https://docs.alfresco.com/5.2/concepts/supported-platforms-ACS.html
There are three different instances we are using: repo (where alfresco.war sits), share (where share.war and ADF sits) and index server (where indexes are maintained).

I install alfresco-rm-enterprise-repo-2.7.0.amp on repo, and alfresco-rm-enterprise-share-2.7.0.amp on share. And restart the servers. RM installation is successful without any errors. But search is not at all working after this.

**Question 1:** Is it possible that after RM installation, some indexes are corrupted, and we need to conduct reindexing ? Can that resolve this issue ?

We tried reindexing the contents by following this link: https://docs.alfresco.com/search-enterprise/tasks/solr-reindex.html
After performing the steps and restarting the alfresco and solr servers, the indexes are not getting built automatically, which ideally should be created.
Here is the error which keeps on coming in the solr/index server logs:
```
2019-12-19 14:37:40.004 ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@4a003cbe_Worker-37) [   ] o.a.s.t.AbstractTracker Tracking failed
org.alfresco.error.AlfrescoRuntimeException: 111929898 GetModelsDiff return status is 403
        at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1181)
        at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:292)
        at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:250)
        at org.alfresco.solr.tracker.ModelTracker.doTrack(ModelTracker.java:210)
        at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:161)
        at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2019-12-19 14:37:50.003 ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@4a003cbe_Worker-8) [   ] o.a.s.t.AbstractTracker Tracking failed
org.alfresco.error.AlfrescoRuntimeException: 111929899 api/solr/aclchangesets return status:403
        at org.alfresco.solr.client.SOLRAPIClient.getAclChangeSets(SOLRAPIClient.java:169)
        at org.alfresco.solr.tracker.AclTracker.getSomeAclChangeSets(AclTracker.java:429)
        at org.alfresco.solr.tracker.AclTracker.trackAclChangeSets(AclTracker.java:652)
        at org.alfresco.solr.tracker.AclTracker.trackRepository(AclTracker.java:309)
        at org.alfresco.solr.tracker.AclTracker.doTrack(AclTracker.java:97)
        at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:161)
        at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
```

And search has stopped working on Alfresco as the indexes are not building.
We also tried uninstalling RM modules from alfresco and share wars. Even after removing the RM amps, the alfresco and share wars are running.
But the index server is still showing the same errors (i.e indexes are not getting built automatically)

**Question 2:** What steps shall we follow to get rid of the above error and make the solr/index server working – 1) Before installing RM  2) After installing RM.

**Comment by tpage-alfresco** [comment]
Hi @srikanth-josyula and thanks for getting in contact.  It looks like you are using enterprise RM, and so you should be able to get more help by getting in contact through the Alfresco support portal.

RM adds the ability to secure documents in new ways - e.g. by using file plan access controls (see RMAfterInvocationProvider in both the enterprise and community versions), or by using security marks (see ExtendedSolrQueryHTTPClient - enterprise only).  RM changes the way documents are queried by filtering out results that the current user does not have access to.  It's possible that this has not interacted well with your custom module.

As far as I'm aware there is nothing in RM that changes the way documents are indexed (besides adding some extra metadata that will be indexed for certain nodes), so I'd be surprised if reindexing helped at all.

Anyway - I'd recommend getting in contact with Alfresco support and taking it from there.
